image: node:lts-alpine

before_script:
  - apk --no-cache --update --virtual build-dependencies add python make g++

stages:
  - test
  # - build
  # - deploy

run-lint-tests:
  stage: test
  script:
    - npm install
    - npm run lint
    - npm test
# cache:
#   paths:
#     - node_modules/

# building:
#   stage: build
#   script:
#     - rm -rf build
#     - sucrase ./src -d ./build --transforms imports
#   artifacts:
#     paths:
#       - node_modules/
#       - build/
