version: '3'

services:
  db:
    image: postgres
    restart: always

    ports:
      - '5432:5432'

    container_name: buildinvest-postgres

  api:
    build: .
    image: buildinvest/web-api

    container_name: web-api-buildinvest

    depends_on:
      - db

    working_dir: /usr/buildinvest/api

    volumes:
      - .:/usr/buildinvest/api
      - /usr/buildinvest/api/node_modules

    ports:
      - '3000:3000'

    env_file: .env

    command: npm start
