version: '3.4'

services:
  db:
    container_name: buildinvest-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '2000:5432'
    # volumes:
    #   - ./db/data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    container_name: buildinvest-api
    build: .
    image: buildinvest-api
    restart: unless-stopped
    working_dir: /usr/buildinvest/api
    volumes:
      - .:/usr/buildinvest/api
      - /usr/buildinvest/api/node_modules
    ports:
      - '3000:3000'
    env_file: .env
    environment:
      DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: npm run dev
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
