version: '3'

services:
  db:
    container_name: buildinvest-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - '2000:5432'

  api:
    container_name: buildinvest-api
    build: .
    image: buildinvest-api
    # restart: always
    working_dir: /usr/buildinvest/api

    volumes:
      - .:/usr/buildinvest/api
      - /usr/buildinvest/api/node_modules
    ports:
      - '3000:3000'

    env_file: .env

    depends_on:
      - db

    command: npm run dev
